### ISSUE TITLE
[功能建议] 自定义规则：多声优并列时其间的间隔符号

### ISSUE THREAD

**Issue by Determancer** [LunarConcerto/MRT#1]
现默认并列方式为间隔` & `，建议增强功能使其格式可自定义。
当前格式示例：`伊ヶ崎綾香 & そらまめ。 & 逢坂成美 & 藍沢夏癒 & 天知遥 & みもりあいの & 花城かざり & 園宮さつき`

**Comment by LunarConcerto** [comment]
可尝试新版本，通过插入一个替换规则达成该效果
