### ISSUE TITLE
求助，小白不清楚是什么地方有问题

### ISSUE THREAD

**Issue by smiledrunk** [LunarConcerto/MRT#2]
[09:36:27 : 程序发生异常！
发生null
在 java.base/javax.crypto.Cipher.getInstance(Cipher.java:546)
在 java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:511)
在 java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:500)
在 java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:82)
在 java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:69)
在 java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:343)
在 java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:556)
在 java.base/java.lang.Class.forName0(Native Method)
在 java.base/java.lang.Class.forName(Class.java:375)
在 java.base/java.security.Provider$Service.getImplClass(Provider.java:1933)
在 java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964)
在 java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878)
在 java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
在 java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
在 java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
在 java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
在 java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
在 java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
在 java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:83)
在 java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336)
在 java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
在 java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81)
在 java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
在 java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
在 java.base/java.net.URL.openConnection(URL.java:1094)
在 org.jsoup.helper.HttpConnection$Response.createConnection(HttpConnection.java:1020)
在 org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:856)
在 org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
在 org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)
在 org.jsoup.helper.HttpConnection.get(HttpConnection.java:353)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.getInfoByRJNumber(DlsiteOnseiRule.java:198)
在 java.base/java.util.Optional.map(Optional.java:260)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.getInfo(DlsiteOnseiRule.java:163)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.run(DlsiteOnseiRule.java:117)
在 com.github.lunarconcerto.magicalrenametool.core.RenameToolController.lambda$onStartButtonAction$2(RenameToolController.java:129)
在 com.github.lunarconcerto.magicalrenametool.func.WorkerManager$1.run(WorkerManager.java:22)
在 java.base/java.lang.Thread.run(Thread.java:833)
请百度搜索问题原因或给我提交issue
]

**Comment by LunarConcerto** [comment]
你好，基本上是因为网络代理的问题。
请检查你的代理软件是否开启全局代理，是否连接上节点，节点网络是否通畅。
如果节点没有问题，那么有可能是代理软件的端口号不一致导致程序没有连接上代理，请查看你的代理软件正在监听的端口号(一般会在代理软件的设置页面)，然后填入到MRT的设置-网络-代理端口中。

**Comment by smiledrunk** [comment]
想请问一下如果人不在墙内所以不开代理这种情况怎么办呢

**Comment by LunarConcerto** [comment]
这个确实没考虑过，晚点我更新看看

**Comment by LunarConcerto** [comment]
尝试新版本
