### ISSUE TITLE
处理某些RJ号会报错

### ISSUE THREAD

**Issue by 114130180** [LunarConcerto/MRT#4]
[09:56:13 : 程序发生异常！
发生No value present
在 java.base/java.util.Optional.get(Optional.java:143)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.findTrTagResource(DlsiteOnseiRule.java:273)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.getInformation(DlsiteOnseiRule.java:216)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.getInfoByRJNumber(DlsiteOnseiRule.java:199)
在 java.base/java.util.Optional.map(Optional.java:260)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.getInfo(DlsiteOnseiRule.java:163)
在 com.github.lunarconcerto.magicalrenametool.rule.impl.dlsite.onsei.DlsiteOnseiRule.run(DlsiteOnseiRule.java:117)
在 com.github.lunarconcerto.magicalrenametool.core.RenameToolController.lambda$onStartButtonAction$2(RenameToolController.java:129)
在 com.github.lunarconcerto.magicalrenametool.func.WorkerManager$1.run(WorkerManager.java:22)
在 java.base/java.lang.Thread.run(Thread.java:833)
请百度搜索问题原因或给我提交issue
]

目前发现的有RJ309834 RJ190259
报错后处理队列会直接停止。希望加一个失败自动跳过的功能。

**Comment by LunarConcerto** [comment]
感谢反馈，最近会更新下

**Comment by LunarConcerto** [comment]
尝试新版本

**Comment by 114130180** [comment]
啊 这。。 启动时报错
![图片](https://user-images.githubusercontent.com/45783569/196023064-02b06c3c-3a80-4f36-a757-9c99f1cec6d1.png)

java.lang.ClassNotFoundException: com.github.lunarconcerto.mrt.MRTStarter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)

**Comment by LunarConcerto** [comment]
别把jar删了

**Comment by 114130180** [comment]
> 别把jar删了

没删jar。运行exe报错，运行jar正常。
