### ISSUE TITLE
[功能建议] 文件夹重命名希望添加中文支持

### ISSUE THREAD

**Issue by TheEnd233** [LunarConcerto/MRT#5]
目前使用程序，文件夹重命名仅支持官方日语名称，某文件夹重命名后如
`[RJ378488] 坊ちゃまに寝取られ堕ちる人妻メイド (スイカ熟成保証委員会)【陽向葵ゅか】`
dlsite官网语言使用简体中文，显示的作品名为
`被少爷寝取堕落的人妻女仆【中文剧本+字幕】`
期望结果
`[RJ378488] 被少爷寝取堕落的人妻女仆【中文剧本+字幕】 (スイカ熟成保証委員会)【陽向葵ゅか】`

**Comment by LunarConcerto** [comment]
新版本在做了还差一点点(:3 っ)=≡=-･∴’Σ[______]

**Comment by LunarConcerto** [comment]
尝试新版本

**Comment by TheEnd233** [comment]
感谢新版本，不过新版本在使用上不太清楚，希望能有个说明手册。

在第二个子窗口上，文件夹的名字和背景一样都是白色，比较难看清楚

![Snipaste_2022-10-15_19-49-06](https://user-images.githubusercontent.com/28785625/195984912-ce635991-fa76-47f0-8ad8-308d1d5adc67.png)

我有点弄不明白重命名规则该如何处理，我的规则如上图，重命名后的文件夹名是

![Snipaste_2022-10-15_19-52-35](https://user-images.githubusercontent.com/28785625/195984941-9c1a8ad6-deba-417c-977a-4c645e7b60d8.png)

但是我想重命名后的文件名格式如下

[号] 作品名 (社团名)【CV】


请问那个规则我该怎么写呢

**Comment by TheEnd233** [comment]
> 

重命名规则已经弄明白了~

**Comment by LunarConcerto** [comment]
已经编写了一些说明，详细请参阅：https://github.com/LunarConcerto/MRT/wiki
